### ISSUE TITLE
Error on flexboxes with only one child

### ISSUE THREAD

**Issue by ghost23** [zoopoetics/react-svg-flexbox#5]
Hi,

I was playing with your flexbox component and I get errors, when I nest them. See here:

https://codesandbox.io/s/j7zlo634rv

Am I doing something wrong or is this a bug?

**Comment by ghost23** [comment]
I think, I already found the issue. It occurs, when there is only one child in Flexbox. Then, here:
https://github.com/zoopoetics/react-svg-flexbox/blob/master/src/index.js#L93
props.children is not an array.

**Comment by zoopoetics** [comment]
@ghost23 Thanks for your input! I'll review your PR shortly.

**Comment by silberjan** [comment]
@zoopoetics i still get this issue also with v1.1.0

specificly i get  

```
e.filter is not a function
TypeError: e.filter is not a function
